# Generated by Django 2.2.6 on 2020-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0004_auto_20200730_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
