# Generated by Django 2.2.6 on 2020-08-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
        ),
    ]
