# Generated by Django 2.2.6 on 2020-08-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_auto_20200804_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='tipo_doacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_doacao.Tipo_doacao'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='tipo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_planta.Tipo_planta'),
        ),
    ]
