# Generated by Django 2.2.6 on 2020-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0004_doacao_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='cidade',
            field=models.CharField(default='mais', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='estado',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
