# Generated by Django 2.2.6 on 2020-08-20 00:24

import apps.endereco.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0005_auto_20200804_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='estado',
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco',
            field=models.CharField(default=1, max_length=255, verbose_name=apps.endereco.models.Endereco),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
