# Generated by Django 2.2.6 on 2020-08-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0008_auto_20200819_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
    ]
