# Generated by Django 2.2.6 on 2020-08-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0009_auto_20200819_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='doacao',
            name='cidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='estado',
            field=models.CharField(default='SC', max_length=255),
            preserve_default=False,
        ),
    ]
