# Generated by Django 2.2.6 on 2020-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0010_auto_20200819_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='nome',
            field=models.CharField(default='Gabriel', max_length=255),
            preserve_default=False,
        ),
    ]
